# Generated by Django 4.2.3 on 2023-07-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LatestNews', '0007_monoranjan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoroscopeNews',
            new_name='upatiyaka',
        ),
    ]
