# Generated by Django 4.2.3 on 2023-07-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LatestNews', '0010_bigyanprabidhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bichar',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='topheadlines',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='topheadlines',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bichar',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bichar',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='bichar',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bigyanprabidhi',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bigyanprabidhi',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bigyanprabidhi',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='bigyanprabidhi',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='monoranjan',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monoranjan',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='monoranjan',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='monoranjan',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='politicalnews',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='politicalnews',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='politicalnews',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='politicalnews',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sportsnews',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sportsnews',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sportsnews',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='topheadlines',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='upatiyaka',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='upatiyaka',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='upatiyaka',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='upatiyaka',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='worldnews',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worldnews',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='worldnews',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='worldnews',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
